[package]
name = "cookie-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-identity = "0.8.0"
actix-session = { version = "0.10.1", features = ["cookie-session"] }
actix-web = "4.9.0"
env_logger = "0.11.5"
log = "0.4.22"
